#repo version 2.0.1
name: Remote Testing for Ract

on:
  push:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  Test-Submit-React-Assessments:
    name: Run Super Duper React Tests
    runs-on: self-hosted
    steps:
      - name: Setting Start Time
        id: time
        uses: nanzm/get-time-action@v1.1
        with:
          timeZone: 8
          format: "YYYY-MM-DDTHH:mm:ssZ"

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.0
        with:
          node-version: "14.x"

      - name: Get Current Config
        run: node C:\\sabio_modules\\sabia\\bin\\index.js get-config
        if: github.repository != 'sabiocode/Starter.react-componentize'
        continue-on-error: false

      - name: Copy Admintests 2
        run: node C:\\sabio_modules\\sabia\\bin\\index.js copy-admintests destination="${{github.workspace}}"
        if: github.repository != 'sabiocode/Starter.react-componentize'
        continue-on-error: false

      # - name: Yarn install
      #   run: yarn install --prefer-offline --network-timeout 600000

      - name: Compile Configured Tests
        run: node C:\\sabio_modules\\sabia\\bin\\index.js compile-configured-test destination="${{github.workspace}}\"
        if: github.repository != 'sabiocode/Starter.react-componentize'
        continue-on-error: false

      - name: Submit Tests to LISA
        run: node C:\\sabio_modules\\sabia\\bin\\index.js send-lisa source="${{github.workspace}}\" branchName="${{github.ref_name}}" projectName="${{github.repository}}"  gitHubUserName="${{github.event.head_commit.author.name}}"
        continue-on-error: false
